### ISSUE TITLE
Document build process 

### ISSUE THREAD

**Issue by gffny** [rgbycch/rgbycch-ios#2]
Would be good to put together a quick 1, 2, 3 list of what to run to clone the repo, build, and run the application

**Comment by seanoshea** [comment]
Good idea! Will get cracking on that.

**Comment by gffny** [comment]
I'll do the same for the rgbycch-rest repo

**Comment by seanoshea** [comment]
See https://github.com/rgbycch/rgbycch-ios/pull/3.

**Comment by seanoshea** [comment]
Closing as #3 has been pulled into master.
